export const WAREHOUSES_LIST = [
  {
    id: 'KHO-HN',
    name: 'Kho Tổng Hà Nội',
    code: 'WH-01',
    address: 'Cụm Công nghiệp Lai Xá, Hoài Đức, Hà Nội',
    type: 'Kho trung tâm Miền Bắc',
    capacity: '5.000 m²',
  },
  {
    id: 'KHO-DN',
    name: 'Kho Trung Chuyển Đà Nẵng',
    code: 'WH-02',
    address: 'KCN Hòa Khánh, Q. Liên Chiểu, TP. Đà Nẵng',
    type: 'Kho trung chuyển Miền Trung',
    capacity: '3.200 m²',
  },
  {
    id: 'KHO-HCM',
    name: 'Kho Tổng TP. Hồ Chí Minh',
    code: 'WH-03',
    address: 'KCN Tân Bình, Q. Tân Phú, TP. Hồ Chí Minh',
    type: 'Kho trung tâm Miền Nam',
    capacity: '6.800 m²',
  },
  {
    id: 'KHO-CT',
    name: 'Kho Chi Nhánh Cần Thơ',
    code: 'WH-04',
    address: 'KCN Trà Nóc 1, Q. Bình Thủy, TP. Cần Thơ',
    type: 'Kho phân phối Miền Tây',
    capacity: '2.500 m²',
  },
  {
    id: 'KHO-HP',
    name: 'Kho Cảng Hải Phòng',
    code: 'WH-05',
    address: 'KCN Đình Vũ, Q. Hải An, TP. Hải Phòng',
    type: 'Kho cảng & tiếp nhận',
    capacity: '3.000 m²',
  },
];

export const TERRITORIES_LIST = [
  {
    id: 'TR-MB',
    name: 'Miền Bắc',
    code: 'MB-REGION',
    provinces: 'Hà Nội, Hải Phòng, Quảng Ninh, Bắc Ninh, Hải Dương...',
    stats: '25 tỉnh/thành',
  },
  {
    id: 'TR-MT',
    name: 'Miền Trung',
    code: 'MT-REGION',
    provinces: 'Đà Nẵng, Thừa Thiên Huế, Quảng Nam, Quảng Ngãi, Bình Định...',
    stats: '14 tỉnh/thành',
  },
  {
    id: 'TR-MN',
    name: 'Miền Nam',
    code: 'MN-REGION',
    provinces: 'TP. Hồ Chí Minh, Bình Dương, Đồng Nai, Bà Rịa - Vũng Tàu...',
    stats: '8 tỉnh/thành',
  },
  {
    id: 'TR-TN',
    name: 'Tây Nguyên',
    code: 'TN-REGION',
    provinces: 'Đắk Lắk, Gia Lai, Kon Tum, Lâm Đồng, Đắk Nông',
    stats: '5 tỉnh/thành',
  },
  {
    id: 'TR-TNB',
    name: 'Tây Nam Bộ',
    code: 'TNB-REGION',
    provinces: 'Cần Thơ, An Giang, Kiên Giang, Tiền Giang, Bến Tre, Cà Mau...',
    stats: '13 tỉnh/thành',
  },
];

export const INITIAL_USERS = [
  {
    id: 'USR-001',
    name: 'Nguyễn Minh Anh',
    email: 'minhanh@sw-system.vn',
    department: 'Phòng Công Nghệ & Hệ Thống',
    roles: ['Quản trị viên'],
    warehouses: [],
    primaryWarehouse: null,
    territories: [],
    status: 'Hoạt động',
  },
  {
    id: 'USR-002',
    name: 'Trần Quốc Bảo',
    email: 'quocbao@sw-system.vn',
    department: 'Phòng Quản Lý Kho Vận',
    roles: ['Quản lý kho'],
    warehouses: ['Kho Tổng Hà Nội', 'Kho Cảng Hải Phòng'],
    primaryWarehouse: 'Kho Tổng Hà Nội',
    territories: [],
    status: 'Hoạt động',
  },
  {
    id: 'USR-003',
    name: 'Lê Thu Hà',
    email: 'thuha@sw-system.vn',
    department: 'Phòng Phát Triển Kinh Doanh',
    roles: ['Nhân viên bán hàng'],
    warehouses: [],
    primaryWarehouse: null,
    territories: ['Miền Bắc'],
    status: 'Hoạt động',
  },
  {
    id: 'USR-004',
    name: 'Phạm Gia Huy',
    email: 'giahuy@sw-system.vn',
    department: 'Chi Nhánh Miền Trung',
    roles: ['Quản lý kho', 'Nhân viên bán hàng'],
    warehouses: ['Kho Trung Chuyển Đà Nẵng'],
    primaryWarehouse: 'Kho Trung Chuyển Đà Nẵng',
    territories: ['Miền Trung', 'Tây Nguyên'],
    status: 'Hoạt động',
  },
  {
    id: 'USR-005',
    name: 'Đặng Hoàng Nam',
    email: 'hoangnam@sw-system.vn',
    department: 'Nhân sự mới tiếp nhận',
    roles: [],
    warehouses: [],
    primaryWarehouse: null,
    territories: [],
    status: 'Chờ phân quyền',
  },
  {
    id: 'USR-006',
    name: 'Đỗ Khánh Linh',
    email: 'khanhlinh@sw-system.vn',
    department: 'Khối Kinh Doanh Miền Nam',
    roles: ['Nhân viên bán hàng'],
    warehouses: [],
    primaryWarehouse: null,
    territories: ['Miền Nam', 'Tây Nam Bộ'],
    status: 'Hoạt động',
  },
];
